-- ==================================================
-- Задание 4: UPDATE и DELETE
-- Уровень: 🟡 Средний
-- Тема: UPDATE SET WHERE, DELETE FROM WHERE
-- Ссылка: notes/sql/01-select-insert.md — "UPDATE", "DELETE"
-- ==================================================
--
-- 1. Обнови возраст Игоря на 21:
--    UPDATE users SET age = 21 WHERE name = 'Игорь';
--
-- 2. Деактивируй пользователя с email dmitry@mail.ru:
--    UPDATE users SET is_active = false WHERE email = 'dmitry@mail.ru';
--
-- 3. Увеличь цену всех товаров на 10%:
--    UPDATE products SET price = price * 1.10;
--
-- 4. Обнови несколько полей одновременно:
--    UPDATE users SET name = 'Игорь Петров', age = 22 WHERE id = 1;
--
-- 5. Удали неактивных пользователей:
--    DELETE FROM users WHERE is_active = false;
--
-- 6. Удали товары с ценой 0:
--    DELETE FROM products WHERE price = 0;
--
-- 7. ВАЖНО: что произойдёт если забыть WHERE в UPDATE/DELETE?
--    Напиши ответ в комментарии.
--
-- 8. Используй UPDATE с RETURNING:
--    UPDATE products SET price = price * 0.9 WHERE id = 1 RETURNING *;
--
-- Пиши SQL ниже:
-- ==================================================
