-- ==================================================
-- Задание 5: Транзакции
-- Уровень: 🟡 Средний
-- Тема: BEGIN, COMMIT, ROLLBACK, ACID
-- Ссылка: notes/sql/03-postgresql.md — "Транзакции"
-- ==================================================
--
-- 1. Простая транзакция — перевод денег между счетами:
--    BEGIN;
--    UPDATE accounts SET balance = balance - 1000 WHERE id = 1;
--    UPDATE accounts SET balance = balance + 1000 WHERE id = 2;
--    COMMIT;
--
-- 2. Транзакция с ROLLBACK — отмена при ошибке:
--    BEGIN;
--    UPDATE accounts SET balance = balance - 1000 WHERE id = 1;
--    -- Проверяем: если баланс стал отрицательным — откат
--    -- SELECT balance FROM accounts WHERE id = 1;
--    -- Если < 0:
--    ROLLBACK;
--
-- 3. Создай таблицу accounts (id, name, balance) и вставь 3 записи.
--    Напиши транзакцию перевода 500₽ от account 1 к account 3.
--
-- 4. Напиши транзакцию создания заказа:
--    BEGIN;
--    INSERT INTO orders (...) VALUES (...);
--    INSERT INTO order_items (...) VALUES (...);
--    UPDATE products SET stock = stock - 1 WHERE id = ...;
--    COMMIT;
--
-- 5. Напиши в комментарии:
--    - Что такое ACID? (Atomicity, Consistency, Isolation, Durability)
--    - Зачем нужны транзакции?
--    - Что произойдёт при ошибке внутри транзакции без ROLLBACK?
--
-- Пиши SQL ниже:
-- ==================================================
