-- ==================================================
-- Задание 6: Комплексная задача — проектирование БД с нуля
-- Уровень: 🔴 Сложный
-- Тема: Все концепции PostgreSQL вместе
-- Ссылка: notes/sql/03-postgresql.md — вся глава
-- ==================================================
--
-- Спроектируй базу данных для блог-платформы:
--
-- 1. Создай таблицы с правильными ограничениями:
--    - users (id, username UNIQUE, email UNIQUE, password_hash, role, created_at)
--      role: CHECK (role IN ('user', 'admin', 'moderator'))
--    - posts (id, title, slug UNIQUE, content, author_id FK, category_id FK,
--      is_published, created_at, updated_at)
--    - categories (id, name, slug UNIQUE, parent_id FK SELF-REFERENCE)
--    - comments (id, content, post_id FK CASCADE, author_id FK SET NULL, created_at)
--    - tags (id, name UNIQUE)
--    - post_tags (post_id FK, tag_id FK, PRIMARY KEY (post_id, tag_id))
--
-- 2. Создай индексы:
--    - posts.slug (уникальный)
--    - posts.author_id (для JOIN)
--    - comments.post_id (для JOIN)
--    - posts.is_published + created_at (составной)
--
-- 3. Вставь тестовые данные:
--    - 3 пользователя (с разными ролями)
--    - 5 категорий (с вложенностью)
--    - 10 постов
--    - 5 тегов
--    - Связи post_tags
--    - 10 комментариев
--
-- 4. Напиши запросы:
--    a) Посты с авторами и категориями (JOIN)
--    b) Количество комментариев к каждому посту (GROUP BY)
--    c) Топ-5 авторов по количеству постов
--    d) Посты с тегом "javascript" (через post_tags)
--    e) Категории с количеством опубликованных постов (HAVING > 0)
--    f) Удаление пользователя (CASCADE для постов и SET NULL для комментариев)
--
-- 5. Транзакция: создание поста с тегами
--    BEGIN;
--    INSERT INTO posts ... RETURNING id;
--    INSERT INTO post_tags (post_id, tag_id) VALUES ...;
--    COMMIT;
--
-- Пиши SQL ниже:
-- ==================================================
