-- ==================================================
-- Задание 2: LEFT JOIN и RIGHT JOIN
-- Уровень: 🟡 Средний
-- Тема: LEFT JOIN, RIGHT JOIN — включая несвязанные записи
-- Ссылка: notes/sql/02-join-group.md — "LEFT JOIN", "RIGHT JOIN"
-- ==================================================
--
-- 1. LEFT JOIN: все категории с количеством товаров (включая пустые):
--    SELECT c.name, COUNT(p.id) AS product_count
--    FROM categories c
--    LEFT JOIN products p ON c.id = p.category_id
--    GROUP BY c.name;
--    (Категории без товаров покажут product_count = 0)
--
-- 2. LEFT JOIN: все клиенты и их заказы (включая клиентов без заказов):
--    Клиенты без заказов покажут NULL в полях заказа.
--
-- 3. Найди клиентов БЕЗ заказов:
--    LEFT JOIN + WHERE o.id IS NULL
--
-- 4. Найди категории БЕЗ товаров:
--    LEFT JOIN + WHERE p.id IS NULL
--
-- 5. Напиши в комментарии:
--    - Чем INNER JOIN отличается от LEFT JOIN?
--    - Когда INNER JOIN "потеряет" строки?
--    - Зачем нужен LEFT JOIN + WHERE ... IS NULL?
--
-- Пиши SQL ниже:
-- ==================================================
