-- ==================================================
-- Задание 4: GROUP BY и HAVING
-- Уровень: 🟡 Средний
-- Тема: GROUP BY, HAVING, группировка с агрегацией
-- Ссылка: notes/sql/02-join-group.md — "GROUP BY", "HAVING"
-- ==================================================
--
-- 1. Количество товаров в каждой категории:
--    SELECT c.name, COUNT(p.id) AS count
--    FROM categories c
--    JOIN products p ON c.id = p.category_id
--    GROUP BY c.name;
--
-- 2. Средняя цена товаров в каждой категории:
--    GROUP BY c.name + AVG(p.price)
--
-- 3. Количество заказов каждого клиента:
--    GROUP BY cu.name + COUNT(o.id)
--
-- 4. Общая сумма заказов по статусу:
--    GROUP BY status + SUM(total_price)
--
-- 5. Категории с более чем 3 товарами (HAVING):
--    GROUP BY c.name HAVING COUNT(p.id) > 3
--
-- 6. Клиенты с общей суммой заказов больше 10000:
--    GROUP BY + HAVING SUM(total_price) > 10000
--
-- 7. Количество клиентов в каждом городе,
--    показать только города с 2+ клиентами:
--    GROUP BY city HAVING COUNT(*) >= 2
--
-- 8. Напиши в комментарии: чем HAVING отличается от WHERE?
--    Почему нельзя WHERE COUNT(*) > 3?
--
-- Пиши SQL ниже:
-- ==================================================
