-- ==================================================
-- Задание 5: Подзапросы (Subqueries)
-- Уровень: 🟡 Средний
-- Тема: Подзапросы в WHERE, FROM, EXISTS
-- Ссылка: notes/sql/02-join-group.md — "Подзапросы"
-- ==================================================
--
-- 1. Товары дороже средней цены:
--    SELECT * FROM products WHERE price > (SELECT AVG(price) FROM products);
--
-- 2. Клиенты, у которых есть хотя бы один заказ:
--    SELECT * FROM customers WHERE id IN (SELECT customer_id FROM orders);
--
-- 3. Самый дорогой товар в каждой категории:
--    WHERE price = (SELECT MAX(price) FROM products p2 WHERE p2.category_id = p.category_id)
--
-- 4. Клиенты, у которых НЕТ заказов (NOT IN):
--    WHERE id NOT IN (SELECT customer_id FROM orders)
--
-- 5. То же самое через NOT EXISTS:
--    WHERE NOT EXISTS (SELECT 1 FROM orders o WHERE o.customer_id = c.id)
--
-- 6. Заказы с суммой выше среднего:
--    WHERE total_price > (SELECT AVG(total_price) FROM orders)
--
-- 7. Напиши в комментарии:
--    - Чем IN отличается от EXISTS?
--    - Когда EXISTS быстрее IN?
--    - Порядок выполнения SQL: FROM → WHERE → GROUP BY → HAVING → SELECT → ORDER BY
--
-- Пиши SQL ниже:
-- ==================================================
