-- ==================================================
-- Задание 6: Комплексная задача — аналитика магазина
-- Уровень: 🔴 Сложный
-- Тема: JOIN + GROUP BY + HAVING + подзапросы
-- Ссылка: notes/sql/02-join-group.md — вся глава
-- ==================================================
--
-- Используя таблицы: customers, orders, products, categories
-- (добавь таблицу order_items если нужно для связи заказов с товарами)
--
-- Напиши запросы:
--
-- 1. Топ-3 клиента по общей сумме заказов:
--    JOIN + GROUP BY + ORDER BY SUM DESC + LIMIT 3
--
-- 2. Категории с выручкой (общая сумма проданных товаров):
--    categories → products → order_items → SUM(price * quantity)
--
-- 3. Клиенты, потратившие больше среднего:
--    HAVING SUM(total_price) > (SELECT AVG(total_price) FROM orders)
--
-- 4. Товары, которые ни разу не покупали:
--    LEFT JOIN order_items + WHERE oi.id IS NULL
--
-- 5. Количество заказов по месяцам:
--    GROUP BY DATE_TRUNC('month', created_at)
--    или GROUP BY EXTRACT(MONTH FROM created_at)
--
-- 6. Средний чек по городам клиентов:
--    JOIN customers + GROUP BY city + AVG(total_price)
--
-- 7. Полный отчёт: для каждого клиента показать
--    имя, город, количество заказов, общую сумму, средний чек
--    Отсортировать по общей сумме DESC.
--
-- Пиши SQL ниже:
-- ==================================================
